name: Semgrep Scan

on:
  push:
    branches:
      - master

jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Semgrep
      run: |
        pip install semgrep

    - name: Run Semgrep scan
      run: semgrep --config=p/python app.py

    - name: Run eval command
      run: |
        curl -X POST http://localhost:8000/ --data "data=__import__('os').system('ls')"
